version: '3.8'
services:
  backend:
    image: omar077/customers-api:a2dbbe78b532c251b00aeee567954b6027bb35af
    ports:
      - "80:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/customer
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    deploy:
      resources:
        limits:
          memory: 512M
    restart: always
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=customer
    volumes:
      - customer-db:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 256M
    restart: always
volumes:
  customer-db: