cors:
  allowed-origins: "*"
  allowed-methods: "*"

logging:
  level:
    org:
      springframework:
        security: TRACE
server:
  error:
    include-message: always


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show_sql: true